# Generated by Django 5.1a1 on 2024-12-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_rename_user_type_id_useraccount_user_type'),
        ('Common', '0004_remove_party_party_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Common.party'),
        ),
    ]
