# Generated by Django 5.1a1 on 2024-09-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electiondata',
            old_name='election_id',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='electiondata',
            old_name='worker_id',
            new_name='worker',
        ),
        migrations.RenameField(
            model_name='electioninfo',
            old_name='candidate_ids',
            new_name='candidates',
        ),
        migrations.RenameField(
            model_name='electioninfo',
            old_name='worker_ids',
            new_name='workers',
        ),
    ]
