# Generated by Django 5.1a1 on 2024-12-18 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_party'),
        ('Election', '0002_rename_election_id_electiondata_election_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='electioninfo',
            name='parties',
            field=models.ManyToManyField(blank=True, related_name='party_info', to='Common.party'),
        ),
        migrations.AlterField(
            model_name='electioninfo',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='candidates_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioninfo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_election', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioninfo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_election', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioninfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_election', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='electioninfo',
            name='workers',
            field=models.ManyToManyField(related_name='workers_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ElectionSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_seat_name', models.TextField(max_length=100)),
                ('election_seat_name_ban', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Common.address')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_election_seat', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_election_seat', to=settings.AUTH_USER_MODEL)),
                ('election_center', models.ManyToManyField(blank=True, related_name='election_center_info', to='Election.electioncenter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_election_seat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
