# Generated by Django 5.1a1 on 2024-12-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0003_electioninfo_parties_alter_electioninfo_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioninfo',
            name='total_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='electioninfo',
            name='total_voter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
