# Generated by Django 5.1a1 on 2024-09-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_corporation_id',
            new_name='city_corporation',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='division_id',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='municipality_id',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='union_id',
            new_name='union',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='upazila_id',
            new_name='upazila',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='ward_id',
            new_name='ward',
        ),
        migrations.RenameField(
            model_name='citycorporation',
            old_name='division_id',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='division_id',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='municipality',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='union',
            old_name='upazila_id',
            new_name='upazila',
        ),
        migrations.RenameField(
            model_name='upazila',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='designation_id',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_account_id',
            new_name='user_account',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='union_id',
            new_name='union',
        ),
    ]
