# Generated by Django 5.1a1 on 2024-12-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_members',
        ),
    ]
